# Generated by Django 2.2.1 on 2019-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='grade',
            field=models.CharField(choices=[('3', '사소'), ('1', '중요'), ('2', '보통')], max_length=30),
        ),
    ]
