# Generated by Django 2.2.1 on 2019-05-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_auto_20190513_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='grade',
            field=models.CharField(choices=[('3', '사소'), ('2', '보통'), ('1', '중요')], max_length=30),
        ),
    ]
