# Generated by Django 2.2.1 on 2019-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_auto_20190514_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='grade',
            field=models.CharField(choices=[('1', '중요'), ('2', '보통'), ('3', '사소')], max_length=30),
        ),
    ]
