# Generated by Django 2.2.1 on 2019-05-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_auto_20190515_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='grade',
            field=models.CharField(choices=[('3', '사소'), ('1', '중요'), ('2', '보통')], max_length=30),
        ),
    ]
