# Generated by Django 2.2.1 on 2019-05-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_auto_20190517_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
