# Generated by Django 2.2.1 on 2019-05-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0007_todoitem_is_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='todoitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todoitem_notifications', to='todolist_app.TodoItem'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='grade',
            field=models.CharField(choices=[('2', '보통'), ('1', '중요'), ('3', '사소')], max_length=30),
        ),
    ]
